/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.cli.Expense;

import picocli.CommandLine;

public class App {

    public static void main(String[] args) {
        CommandLine cmd = new CommandLine(new Expense());
        cmd.execute(args);

    }

}
